apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: product-services-dev
  labels:
    app: postgres
type: Opaque
data:
  # Base64 encoded "postgres"
  # To encode: echo -n "your-password" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
