apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: product-services-dev
data:
  DB_HOST: "postgres-service"
  DB_NAME: "inventorydb"
  DB_USER: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SERVER_PORT: "8083"
